### PR TITLE
Allow arbitrary haproxy_server_options to be supplied to HAProxy.

### PR DESCRIPTION
**Pull request by jolynch**
This allows operators to declare that particular backends are backups, should have different failure modes (fall/rise), healthcheck rates, etc ... We need to add support to nerve to be able to pass these through, but this should help with #100.

If you want restarts to be forced when the state changes, you must use
the state file.

### CODE REVIEW

**Comment by Jaykah** [comment]
That was fast, thanks! Was just about to address this. 

Have tested this and can confirm that it is working as expected with all of the options I need.

Also, worth noting that if someone wants to do http checks on custom ports, they will have to add       - ```"option httpchk /"``` to haproxy section, in addition to ```haproxy_server_options: "check port 9203"```

**Comment by jnb** [comment]
:+1: 

I like using the state file instead of querying haproxy.  In the future I think it might be worth abstracting this component out some more.

**Comment by Jaykah** [comment]
Just tested https://github.com/airbnb/nerve/pull/75 and wanted to follow up on this pull request - for some reason, when Synapse is getting data from Zookeeper that includes haproxy_server_options it does not use them, generating a Haproxy config without those options.

**Comment by jolynch** [comment]
Did you enable the state file?

**Comment by Jaykah** [comment]
@jolynch No, state cache is not enabled.

**Comment by jolynch** [comment]
@Jaykah Heh I forgot to merge #144 . I've merged it now and can start testing on our infra next week (after thanksgiving).

Remember to enable the `state_file_path` from https://github.com/airbnb/synapse#configuring-haproxy so that when the haproxy server options change synapse will restart haproxy.

**Pull request merged**
